site_name: Social data science key concepts

nav:
  - Home: index.md
  - Social: social.md
  - Data: data.md
  - Science: science.md
  - Tools: tools.md

theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.png

extra_css:
  - stylesheets/extra.css

plugins: []
